### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Hi,

The change in the PR is NOT tested. I just know I couldn't install without removing (only) DataFrames.jl first. So that seems like the most important package to support at the latest version.

Your package/plot type (and others I learned of), seems very intriguing, so I want this package to work faster. It takes 21 sec. to load, with -O1 opt. down to 15 sec. but even using (almost) all the tricks in the book, I only get (still slower than most other plotting packages):
```
$ ~/julia-1.7.0-rc3/bin/julia -O0 --compile=min

julia> @time using CMPlot
  5.134907 seconds (5.82 M allocations: 373.272 MiB, 4.08% gc time, 2.53% compilation time)
```

With a simple change that could be the default speed to for your package (as done in Plots.jl, main file).

Adding your package downgraded a lot of packages (and upgraded 8 packages in Project, plus more in Manifest) since I forgot to use the non-default:

```
pkg> add --preserve=all CMPlots
```

```
  [a93c6f00] ↓ DataFrames v1.2.2 ⇒ v0.22.7
  [1313f7d8] ↓ DataFramesMeta v0.9.1 ⇒ v0.8.0

  [262411bb] ↓ OutlierDetection v0.2.0 ⇒ v0.1.0

    Updating `~/.julia/environments/v1.7/Manifest.toml`

  [324d7699] ↓ CategoricalArrays v0.10.1 ⇒ v0.9.7

  [31c24e10] ↓ Distributions v0.25.17 ⇒ v0.24.18

  [1a297f60] ↓ FillArrays v0.12.6 ⇒ v0.11.9

  [e80e1ace] ↓ MLJModelInterface v1.3.2 ⇒ v0.4.1

  [e1d29d7a] ↓ Missings v1.0.2 ⇒ v0.4.5

  [321657f4] ↓ ScientificTypes v2.3.0 ⇒ v1.1.2

  [64bff920] ↓ StatisticalTraits v2.1.0 ⇒ v0.1.1
```

**Comment by PallHaraldsson** [comment]
The slowness of loading your package is mostly about your dependencies, but you can fix to a large degree with newer versions:

```
julia> @time using PlotlyJS
 16.174547 seconds (33.01 M allocations: 1.307 GiB, 5.23% gc time, 87.69% compilation time)

julia> @time using DataFrames
  1.628867 seconds (2.27 M allocations: 156.820 MiB, 3.17% gc time, 0.70% compilation time)

julia> @time using Distributions
  0.864424 seconds (1.35 M allocations: 85.829 MiB, 22.50% compilation time)

(@v1.7) pkg> add PlotlyJS@v0.18.8

julia> @time using PlotlyJS
  8.973865 seconds (17.29 M allocations: 735.415 MiB, 6.53% gc time, 87.08% compilation time)

$ ~/julia-1.7.0-rc3/bin/julia -O0 --compile=min

julia> @time using PlotlyJS
  1.600965 seconds (2.37 M allocations: 151.253 MiB, 4.72% gc time, 6.48% compilation time)
```

**Comment by PallHaraldsson** [comment]
I'm not sure why PR CI is failing, it seems to work for me, at least loading, and I confirm it faster:
```
import Pkg; Pkg.add(url="https://github.com/PallHaraldsson/CMPlot.jl", rev="patch-1")

$ ~/julia-1.7.0-rc3/bin/julia -O0 --compile=min

julia> @time using CMPlot
  4.389788 seconds (6.11 M allocations: 393.030 MiB, 7.96% gc time, 2.57% compilation time)

while still bad, but better with default:

julia> @time using CMPlot
 13.439906 seconds (23.35 M allocations: 1.076 GiB, 5.52% gc time, 71.77% compilation time)
```

**Comment by g-insana** [comment]
> I'm not sure why PR CI is failing, it seems to work for me, at least loading, and I confirm it faster:

It seems for 1.3 it's having problems with the Artifacts module.

**Comment by g-insana** [comment]
Thank you for updating dependencies and testing the speeds. Merging the PR

**Pull request merged**
